name: food_delivery
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  sizer: ^3.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.9
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_advanced_drawer: ^1.3.6
  country_picker: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/desserts/
    - assets/images/food/
    - assets/images/seafood/
    - assets/fonts/
    - assets/icons/
    - .env
  
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700  # Bold weight
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500  # Medium weight
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400  # Regular weight
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 200  # Light weight
        

